$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/fault-0031/policy-valid-fault-plus10.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:17:04Z"
  generation: 1
  name: policy-valid-fault-plus10
  namespace: lab
  resourceVersion: "1940"
  uid: 1a35d209-a140-4bc2-a9ba-dba1e90e3f6d
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
