$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/fault-0031/serviceprofile-valid-fault-plus10.request.yaml -o yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2026-09-14T19:17:04Z"
  generation: 1
  name: serviceprofile-valid-fault-plus10
  namespace: lab
  resourceVersion: "1943"
  uid: 2832158f-38f8-4233-808c-2020c92cfc24
spec:
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: 10s
[exit 0]
