apiVersion: v1
kind: Pod
metadata:
  name: inject-probe-pre-2
  namespace: lab
  labels:
    app: inject-probe
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  containers:
    - name: idle
      image: docker.io/library/busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
      command: ["sh", "-c", "sleep 3600"]
