$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/policy-valid-pre-1.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:06:50Z"
  generation: 1
  name: policy-valid-pre-1
  namespace: lab
  resourceVersion: "1073"
  uid: d52c5dc7-70d5-400e-8b0d-4b7abcb7e1a4
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
