$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/policy-valid-pre-3.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:07:49Z"
  generation: 1
  name: policy-valid-pre-3
  namespace: lab
  resourceVersion: "1151"
  uid: 2b3b55bb-cf84-4624-9958-868f3a1ec090
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
