$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/policy-valid-pre-16.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:14:21Z"
  generation: 1
  name: policy-valid-pre-16
  namespace: lab
  resourceVersion: "1705"
  uid: af4dcdd6-f81f-4d9f-89f5-f9991e2387ee
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
