$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/policy-valid-pre-11.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:11:50Z"
  generation: 1
  name: policy-valid-pre-11
  namespace: lab
  resourceVersion: "1493"
  uid: 9f706d55-4b67-4897-b855-a2541c623243
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
