$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/policy-valid-fault-minus10.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:16:28Z"
  generation: 1
  name: policy-valid-fault-minus10
  namespace: lab
  resourceVersion: "1875"
  uid: 15848ee7-ffce-4c88-8c79-a9733209199b
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
