$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/policy-valid-pre-15.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:13:50Z"
  generation: 1
  name: policy-valid-pre-15
  namespace: lab
  resourceVersion: "1661"
  uid: b458e0c4-c779-4d75-9f5f-a207909f6331
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
