$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/policy-valid-pre-12.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:12:19Z"
  generation: 1
  name: policy-valid-pre-12
  namespace: lab
  resourceVersion: "1535"
  uid: 716d0612-3ffe-43be-b7a3-6e27ef3363d2
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
