$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/policy-valid-pre-6.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:09:19Z"
  generation: 1
  name: policy-valid-pre-6
  namespace: lab
  resourceVersion: "1275"
  uid: 1287c7dc-0fbf-4236-9d9f-403642804141
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
