$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/policy-valid-pre-14.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:13:20Z"
  generation: 1
  name: policy-valid-pre-14
  namespace: lab
  resourceVersion: "1616"
  uid: 3eb471aa-445c-41a9-88bd-b608b9ff44e1
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
