$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/policy-valid-pre-13.request.yaml -o yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  creationTimestamp: "2026-09-14T19:12:50Z"
  generation: 1
  name: policy-valid-pre-13
  namespace: lab
  resourceVersion: "1576"
  uid: e1e9a536-c60c-400e-9e81-a3a2955b8cd1
spec:
  networks:
  - cidr: 10.255.0.0/16
[exit 0]
