apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: serviceprofile-valid-fault-minus60
  namespace: lab
spec:
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s
