$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/serviceprofile-valid-fault-minus10.request.yaml -o yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2026-09-14T19:16:28Z"
  generation: 1
  name: serviceprofile-valid-fault-minus10
  namespace: lab
  resourceVersion: "1877"
  uid: 7395e1dc-d264-465e-9a42-a1ee2f782cde
spec:
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: 10s
[exit 0]
