$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/serviceprofile-valid-pre-14.request.yaml -o yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2026-09-14T19:13:20Z"
  generation: 1
  name: serviceprofile-valid-pre-14
  namespace: lab
  resourceVersion: "1618"
  uid: ea50045c-1b31-4558-aadf-b6153e44be97
spec:
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: 10s
[exit 0]
