$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/serviceprofile-valid-pre-3.request.yaml -o yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2026-09-14T19:07:50Z"
  generation: 1
  name: serviceprofile-valid-pre-3
  namespace: lab
  resourceVersion: "1155"
  uid: 33e0a782-d9c3-4513-b7ed-becdb2740015
spec:
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: 10s
[exit 0]
