$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/serviceprofile-valid-pre-1.request.yaml -o yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2026-09-14T19:06:50Z"
  generation: 1
  name: serviceprofile-valid-pre-1
  namespace: lab
  resourceVersion: "1075"
  uid: 09cba4b0-ce41-4de2-bd1d-3e840694bc18
spec:
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: 10s
[exit 0]
