$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/serviceprofile-valid-pre-16.request.yaml -o yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2026-09-14T19:14:21Z"
  generation: 1
  name: serviceprofile-valid-pre-16
  namespace: lab
  resourceVersion: "1707"
  uid: 8d2e4f37-5a30-4231-afdd-02e58a0b6857
spec:
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: 10s
[exit 0]
