$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/serviceprofile-valid-fault-minus60.request.yaml -o yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2026-09-14T19:15:38Z"
  generation: 1
  name: serviceprofile-valid-fault-minus60
  namespace: lab
  resourceVersion: "1819"
  uid: 7f0d9eaf-e111-4bc6-b657-6b517320d13b
spec:
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: 10s
[exit 0]
