$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/pre-fault/serviceprofile-valid-pre-4.request.yaml -o yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2026-09-14T19:08:20Z"
  generation: 1
  name: serviceprofile-valid-pre-4
  namespace: lab
  resourceVersion: "1197"
  uid: 39d34360-3268-49e9-a021-5f08b9fb0f63
spec:
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: 10s
[exit 0]
