$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/fault-0085/serviceprofile-valid-post-1.request.yaml -o yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2026-09-14T19:17:58Z"
  generation: 1
  name: serviceprofile-valid-post-1
  namespace: lab
  resourceVersion: "2025"
  uid: bfb6f490-abcd-4e5b-938a-7188adfb1e11
spec:
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: 10s
[exit 0]
