apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: mixed-env
  name: echo-http
spec:
  podSelector:
    matchLabels: { app: echo }
  port: http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  namespace: mixed-env
  name: allow-edge
spec:
  identities:
    - "spiffe://root.linkerd.cluster.local/edge-echo"
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  namespace: mixed-env
  name: echo-allow-edge
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: echo-http
  requiredAuthenticationRefs:
    - name: allow-edge
      kind: MeshTLSAuthentication
      group: policy.linkerd.io
