apiVersion: workload.linkerd.io/v1beta1
kind: ExternalWorkload
metadata:
  name: edge-echo
  namespace: mixed-env
  labels:
    location: vm
    app: edge-echo
    workload_name: edge-echo
spec:
  meshTLS:
    identity: "spiffe://root.linkerd.cluster.local/edge-echo"
    serverName: "edge-echo.cluster.local"
  workloadIPs:
  - ip: "__EDGE_ADDR__"
  ports:
  - port: 80
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: edge-echo
  namespace: mixed-env
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: edge-echo
