$ kubectl get -f runs/_discovery/20260914T190446Z-40-webhook-unavailable-ignore/admission/baseline/serviceprofile-valid-baseline.request.yaml -o yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2026-09-14T19:06:43Z"
  generation: 1
  name: serviceprofile-valid-baseline
  namespace: lab
  resourceVersion: "1057"
  uid: d07b46f0-a0c8-49cd-a53b-887d71eeda3e
spec:
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: 10s
[exit 0]
